// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinClinic.Model;

namespace WinClinic.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190103134838_IsQuantitySet")]
    partial class IsQuantitySet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WinClinic.Model.Accounts.Schemes", b =>
                {
                    b.Property<Guid>("SchemesID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Status");

                    b.HasKey("SchemesID");

                    b.ToTable("Schemes");

                    b.HasData(
                        new { SchemesID = new Guid("7a45e43c-138f-4d59-8fd8-561da7862834"), Description = "National Health Insurance", Scheme = "NHIS", Status = true }
                    );
                });

            modelBuilder.Entity("WinClinic.Model.Accounts.ServiceCodes", b =>
                {
                    b.Property<Guid>("ServiceCodesID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<decimal>("Cost");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<Guid>("SchemesID");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("ServicesID");

                    b.Property<bool>("Status");

                    b.HasKey("ServiceCodesID");

                    b.HasIndex("SchemesID");

                    b.HasIndex("ServicesID");

                    b.ToTable("ServiceCodes");
                });

            modelBuilder.Entity("WinClinic.Model.Accounts.Services", b =>
                {
                    b.Property<Guid>("ServicesID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("ServiceGroup")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("ServiceTypesID");

                    b.Property<bool>("Status");

                    b.HasKey("ServicesID");

                    b.HasIndex("ServiceTypesID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("WinClinic.Model.ConsultingRoom.AdmissionInstructions", b =>
                {
                    b.Property<long>("AdmissionInstructionsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Instructions")
                        .HasMaxLength(200);

                    b.Property<long>("PatientAdmissionsID");

                    b.HasKey("AdmissionInstructionsID");

                    b.HasIndex("PatientAdmissionsID");

                    b.ToTable("AdmissionInstructions");
                });

            modelBuilder.Entity("WinClinic.Model.ConsultingRoom.Diagnoses", b =>
                {
                    b.Property<Guid>("DiagnosesID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .HasMaxLength(30);

                    b.HasKey("DiagnosesID");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("WinClinic.Model.ConsultingRoom.DiagnosticCodes", b =>
                {
                    b.Property<Guid>("DiagnosticCodesID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("DiagnosesID");

                    b.Property<string>("GDRG")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ICDCode")
                        .HasMaxLength(15);

                    b.Property<Guid>("SchemesID");

                    b.Property<double>("Tariff");

                    b.HasKey("DiagnosticCodesID");

                    b.HasIndex("DiagnosesID");

                    b.HasIndex("SchemesID");

                    b.ToTable("DiagnosticCodes");
                });

            modelBuilder.Entity("WinClinic.Model.ConsultingRoom.PatientConsultation", b =>
                {
                    b.Property<Guid>("PatientConsultationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Complaints")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Examination")
                        .HasMaxLength(500);

                    b.Property<Guid>("PatientAttendanceID");

                    b.Property<string>("PhysicianNotes")
                        .HasMaxLength(500);

                    b.Property<string>("UserName");

                    b.HasKey("PatientConsultationID");

                    b.HasIndex("PatientAttendanceID");

                    b.ToTable("PatientConsultations");
                });

            modelBuilder.Entity("WinClinic.Model.ConsultingRoom.PatientDiagnosis", b =>
                {
                    b.Property<Guid>("PatientDiagnosisID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<Guid>("DiagnosticCodesID");

                    b.Property<Guid>("PatientAttendanceID");

                    b.Property<string>("UserName")
                        .HasMaxLength(30);

                    b.HasKey("PatientDiagnosisID");

                    b.HasIndex("DiagnosticCodesID");

                    b.HasIndex("PatientAttendanceID");

                    b.ToTable("PatientDiagnosis");
                });

            modelBuilder.Entity("WinClinic.Model.DrugCodes", b =>
                {
                    b.Property<Guid>("DrugCodesID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<decimal>("Cost");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("DrugCode")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<Guid>("DrugsID");

                    b.Property<Guid>("SchemesID");

                    b.HasKey("DrugCodesID");

                    b.HasIndex("DrugsID");

                    b.HasIndex("SchemesID");

                    b.ToTable("DrugCodes");
                });

            modelBuilder.Entity("WinClinic.Model.Laboratory.LabGroups", b =>
                {
                    b.Property<short>("LabGroupsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<decimal>("Cost");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("LabGroupsID");

                    b.ToTable("LabGroups");
                });

            modelBuilder.Entity("WinClinic.Model.Laboratory.LaboratoryServices", b =>
                {
                    b.Property<Guid>("LaboratoryServicesID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<short>("LabGroupsID");

                    b.Property<string>("LaboratoryProcedure")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("LaboratoryServicesID");

                    b.HasIndex("LabGroupsID");

                    b.ToTable("LaboratoryServices");
                });

            modelBuilder.Entity("WinClinic.Model.Laboratory.PatientLaboratoryServices", b =>
                {
                    b.Property<long>("PatientLaboratoryServicesID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountsOfficer")
                        .HasMaxLength(30);

                    b.Property<decimal>("Amount");

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime?>("DatePaid");

                    b.Property<DateTime>("DateRequested");

                    b.Property<DateTime>("DateServed");

                    b.Property<bool>("IsPaid");

                    b.Property<bool>("IsServed");

                    b.Property<string>("LabOfficer")
                        .HasMaxLength(30);

                    b.Property<Guid>("LaboratoryServicesID");

                    b.Property<string>("Notes")
                        .HasMaxLength(100);

                    b.Property<Guid>("PatientAttendanceID");

                    b.Property<string>("RequestingOfficer")
                        .HasMaxLength(30);

                    b.Property<string>("Results")
                        .HasMaxLength(200);

                    b.HasKey("PatientLaboratoryServicesID");

                    b.HasIndex("LaboratoryServicesID");

                    b.HasIndex("PatientAttendanceID");

                    b.ToTable("PatientLaboratoryServices");
                });

            modelBuilder.Entity("WinClinic.Model.NursingCare.DrugAdministrations", b =>
                {
                    b.Property<long>("DrugAdministrationsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("PatientMedicationsID");

                    b.Property<Guid?>("PatientMedicationsID1");

                    b.Property<string>("UserName")
                        .HasMaxLength(30);

                    b.HasKey("DrugAdministrationsID");

                    b.HasIndex("PatientMedicationsID1");

                    b.ToTable("DrugAdministrations");
                });

            modelBuilder.Entity("WinClinic.Model.NursingCare.NursesWards", b =>
                {
                    b.Property<int>("NursesWardsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserName")
                        .HasMaxLength(30);

                    b.Property<string>("WardName");

                    b.HasKey("NursesWardsID");

                    b.HasIndex("WardName");

                    b.ToTable("NursesWards");
                });

            modelBuilder.Entity("WinClinic.Model.NursingCare.PatientAdmissions", b =>
                {
                    b.Property<long>("PatientAdmissionsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DateAdmitted");

                    b.Property<DateTime?>("DateDischarged");

                    b.Property<bool>("Discharged");

                    b.Property<string>("PatientsID")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .HasMaxLength(30);

                    b.Property<string>("WardName")
                        .HasMaxLength(50);

                    b.HasKey("PatientAdmissionsID");

                    b.HasIndex("PatientsID");

                    b.HasIndex("WardName");

                    b.ToTable("PatientAdmissions");
                });

            modelBuilder.Entity("WinClinic.Model.NursingCare.PatientMedications", b =>
                {
                    b.Property<Guid>("PatientMedicationsID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<byte>("Frequency");

                    b.Property<byte>("NumberOfDays");

                    b.Property<string>("PatientsID")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .HasMaxLength(30);

                    b.HasKey("PatientMedicationsID");

                    b.HasIndex("PatientsID");

                    b.ToTable("PatientMedications");
                });

            modelBuilder.Entity("WinClinic.Model.OPD.OPD", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DateSeen");

                    b.Property<double>("Diastolic");

                    b.Property<string>("FirstAid")
                        .HasMaxLength(500);

                    b.Property<string>("History")
                        .HasMaxLength(500);

                    b.Property<Guid>("PatientAttendanceID");

                    b.Property<double>("Pulse");

                    b.Property<double>("Respiration");

                    b.Property<double>("Systolic");

                    b.Property<double>("Temperature");

                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.Property<double>("Weight");

                    b.HasKey("ID");

                    b.HasIndex("PatientAttendanceID");

                    b.ToTable("OpdHistory");
                });

            modelBuilder.Entity("WinClinic.Model.Pharmacy.Drugs", b =>
                {
                    b.Property<Guid>("DrugsID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("GroupName")
                        .HasMaxLength(100);

                    b.HasKey("DrugsID");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("WinClinic.Model.Pharmacy.PatientDrugs", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AmountPaid");

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DatePaid");

                    b.Property<DateTime>("DateQuantitySet");

                    b.Property<DateTime>("DateRequested");

                    b.Property<DateTime>("DateServed");

                    b.Property<Guid>("DrugCodesID");

                    b.Property<byte>("Frequency");

                    b.Property<bool>("IsCompleted");

                    b.Property<bool>("IsPaid");

                    b.Property<bool>("IsQuantitySet");

                    b.Property<bool>("IsServed");

                    b.Property<byte>("NumberOfDays");

                    b.Property<Guid>("PatientAttendanceID");

                    b.Property<byte>("QuantityIssued");

                    b.Property<byte>("QuantityRequested");

                    b.Property<string>("Receipt")
                        .HasMaxLength(20);

                    b.Property<string>("ReceivingOficcer")
                        .HasMaxLength(30);

                    b.Property<string>("RequestingOficcer")
                        .HasMaxLength(30);

                    b.Property<string>("ServingOficcer")
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.HasIndex("DrugCodesID");

                    b.HasIndex("PatientAttendanceID");

                    b.ToTable("PatientDrugs");
                });

            modelBuilder.Entity("WinClinic.Model.Records.PatientAttendance", b =>
                {
                    b.Property<Guid>("PatientAttendanceID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DateClosed");

                    b.Property<DateTime>("DateSeen");

                    b.Property<bool>("IsActive");

                    b.Property<string>("PatientsID")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("PatientAttendanceID");

                    b.HasIndex("PatientsID");

                    b.ToTable("PatientAttendance");
                });

            modelBuilder.Entity("WinClinic.Model.Records.PatientDetails", b =>
                {
                    b.Property<string>("PatientsID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("DependentID")
                        .HasMaxLength(20);

                    b.Property<bool>("IsCapitated");

                    b.Property<bool>("IsDependent");

                    b.Property<string>("Kin")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("KinContact")
                        .HasMaxLength(20);

                    b.Property<string>("SchemeNumber")
                        .HasMaxLength(20);

                    b.Property<Guid>("SchemesID");

                    b.Property<bool>("Status");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("PatientsID");

                    b.ToTable("PatientDetails");
                });

            modelBuilder.Entity("WinClinic.Model.Records.Patients", b =>
                {
                    b.Property<string>("PatientsID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("OtherNames")
                        .HasMaxLength(50);

                    b.Property<Guid>("SchemesID");

                    b.Property<string>("Surname")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.HasKey("PatientsID");

                    b.HasIndex("SchemesID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("WinClinic.Model.Services.PatientServices", b =>
                {
                    b.Property<Guid>("PatientServicesID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("DatePaid");

                    b.Property<DateTime>("DateRequested");

                    b.Property<DateTime>("DateServed");

                    b.Property<byte>("Frequency");

                    b.Property<bool>("IsPaid");

                    b.Property<bool>("IsServed");

                    b.Property<byte>("NumberOfDays");

                    b.Property<Guid>("PatientAttendanceID");

                    b.Property<string>("Receipt")
                        .HasMaxLength(15);

                    b.Property<string>("ReceivingOficcer")
                        .HasMaxLength(30);

                    b.Property<string>("RequestingOficcer")
                        .HasMaxLength(30);

                    b.Property<Guid>("ServiceCodesID");

                    b.Property<decimal>("ServiceCost");

                    b.Property<string>("ServingOficcer");

                    b.HasKey("PatientServicesID");

                    b.HasIndex("PatientAttendanceID");

                    b.HasIndex("ServiceCodesID");

                    b.ToTable("PatientServices");
                });

            modelBuilder.Entity("WinClinic.Model.Services.ServiceTypes", b =>
                {
                    b.Property<Guid>("ServiceTypesID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<bool>("Status");

                    b.HasKey("ServiceTypesID");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("WinClinic.Model.Wards", b =>
                {
                    b.Property<string>("WardName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<byte>("Capacity");

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("PatientType")
                        .HasMaxLength(30);

                    b.Property<bool>("Status");

                    b.HasKey("WardName");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("WinClinic.Model.Staff.Staff", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");


                    b.ToTable("Staff");

                    b.HasDiscriminator().HasValue("Staff");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.Accounts.ServiceCodes", b =>
                {
                    b.HasOne("WinClinic.Model.Accounts.Schemes", "Schemes")
                        .WithMany("ServiceCodes")
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WinClinic.Model.Accounts.Services", "Services")
                        .WithMany("ServiceCodes")
                        .HasForeignKey("ServicesID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.Accounts.Services", b =>
                {
                    b.HasOne("WinClinic.Model.Services.ServiceTypes", "ServiceTypes")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTypesID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.ConsultingRoom.AdmissionInstructions", b =>
                {
                    b.HasOne("WinClinic.Model.NursingCare.PatientAdmissions", "PatientAdmissions")
                        .WithMany("AdmissionInstructions")
                        .HasForeignKey("PatientAdmissionsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.ConsultingRoom.DiagnosticCodes", b =>
                {
                    b.HasOne("WinClinic.Model.ConsultingRoom.Diagnoses", "Diagnoses")
                        .WithMany("DiagnosticCodes")
                        .HasForeignKey("DiagnosesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WinClinic.Model.Accounts.Schemes", "Schemes")
                        .WithMany("DiagnosticCodes")
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.ConsultingRoom.PatientConsultation", b =>
                {
                    b.HasOne("WinClinic.Model.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendanceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.ConsultingRoom.PatientDiagnosis", b =>
                {
                    b.HasOne("WinClinic.Model.ConsultingRoom.DiagnosticCodes", "DiagnosticCodes")
                        .WithMany("PatientDiagnoses")
                        .HasForeignKey("DiagnosticCodesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WinClinic.Model.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendanceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.DrugCodes", b =>
                {
                    b.HasOne("WinClinic.Model.Pharmacy.Drugs", "Drugs")
                        .WithMany("DrugCodes")
                        .HasForeignKey("DrugsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WinClinic.Model.Accounts.Schemes", "Schemes")
                        .WithMany("DrugCodes")
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.Laboratory.LaboratoryServices", b =>
                {
                    b.HasOne("WinClinic.Model.Laboratory.LabGroups", "LabGroup")
                        .WithMany("LaboratoryServices")
                        .HasForeignKey("LabGroupsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.Laboratory.PatientLaboratoryServices", b =>
                {
                    b.HasOne("WinClinic.Model.Laboratory.LaboratoryServices", "LaboratoryService")
                        .WithMany("PatientLaboratoryServices")
                        .HasForeignKey("LaboratoryServicesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WinClinic.Model.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendanceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.NursingCare.DrugAdministrations", b =>
                {
                    b.HasOne("WinClinic.Model.NursingCare.PatientMedications", "PatientMedications")
                        .WithMany("DrugAdministration")
                        .HasForeignKey("PatientMedicationsID1");
                });

            modelBuilder.Entity("WinClinic.Model.NursingCare.NursesWards", b =>
                {
                    b.HasOne("WinClinic.Model.Wards", "Wards")
                        .WithMany("NursesWards")
                        .HasForeignKey("WardName");
                });

            modelBuilder.Entity("WinClinic.Model.NursingCare.PatientAdmissions", b =>
                {
                    b.HasOne("WinClinic.Model.Records.Patients", "Patients")
                        .WithMany()
                        .HasForeignKey("PatientsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WinClinic.Model.Wards", "Wards")
                        .WithMany("PatientAdmissioins")
                        .HasForeignKey("WardName");
                });

            modelBuilder.Entity("WinClinic.Model.NursingCare.PatientMedications", b =>
                {
                    b.HasOne("WinClinic.Model.Records.Patients", "Patients")
                        .WithMany()
                        .HasForeignKey("PatientsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.OPD.OPD", b =>
                {
                    b.HasOne("WinClinic.Model.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendanceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.Pharmacy.PatientDrugs", b =>
                {
                    b.HasOne("WinClinic.Model.DrugCodes", "Drugcodes")
                        .WithMany()
                        .HasForeignKey("DrugCodesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WinClinic.Model.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendanceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.Records.PatientAttendance", b =>
                {
                    b.HasOne("WinClinic.Model.Records.Patients", "Patients")
                        .WithMany("PatientAttendance")
                        .HasForeignKey("PatientsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.Records.PatientDetails", b =>
                {
                    b.HasOne("WinClinic.Model.Records.Patients", "Patients")
                        .WithOne("PatientDetails")
                        .HasForeignKey("WinClinic.Model.Records.PatientDetails", "PatientsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.Records.Patients", b =>
                {
                    b.HasOne("WinClinic.Model.Accounts.Schemes", "Schemes")
                        .WithMany("Patients")
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WinClinic.Model.Services.PatientServices", b =>
                {
                    b.HasOne("WinClinic.Model.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendanceID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WinClinic.Model.Accounts.ServiceCodes", "ServiceCodes")
                        .WithMany()
                        .HasForeignKey("ServiceCodesID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
